#!/usr/bin/env python3
"""Generate MuJoCo assets for the peg + the two hole blocks from cad/Peg-Hole/TaskOrientedGrasping/stls.

Measured from the CAD meshes (mm):
  peg    : 200 long. SQUARE end 41.5 x 41.5 x 95 (z 5.04..100.04) -> 8 mm loft -> CYLINDRICAL end D50 x 97 (z 108.2..205.04).
  circle hole block : 70 x 70 x 44 (5 mm rounded vertical corners), blind cylindrical hole D55.5, 41 deep, 3 mm back wall.
  square hole block : 70 x 70 x 44,                                  blind square hole 46.7 x 46.7, 41 deep, 3 mm back wall.
  => per-side clearance ~ 2.6 mm (square) / 2.75 mm (round).
Frames: peg origin = volume centroid, +z toward the circular end.  hole frame origin = centre of the hole OPENING,
+z pointing OUT of the hole (cavity is z in [-0.041, 0], back wall [-0.044, -0.041]).
Masses (user): peg ~100 g, each hole block ~50 g.  Surface friction is a guess.  Whether the hole blocks are fixed to the table in the real setup is unknown (HOLES_FREE).
Outputs: assets/peg_hole/{peg_sq.stl,peg_circ.stl,hole_circle_vis.stl,hole_square_vis.stl,peg_hole_assets.xml, peg_hole_test.xml}
"""
import struct
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
CAD = HERE.parent / "cad" / "Peg-Hole" / "TaskOrientedGrasping" / "stls"
OUT = HERE / "assets" / "peg_hole"
MESH = OUT / "meshes"
PEG_MASS_KG = 0.10          # user: peg ~100 g
HOLE_MASS_KG = 0.05         # user: each hole block ~50 g
HOLES_FREE = False          # True: hole blocks are free bodies on the table (unknown whether they are fixed/taped in the real setup)
C_XY = 35.35                # assembly-frame xy centre of the peg / holes (mm)


def load_stl(path):
    import re
    b = Path(path).read_bytes()
    if b[:5] == b"solid" and b"facet" in b[:400]:
        return np.array(re.findall(rb"vertex\s+(\S+)\s+(\S+)\s+(\S+)", b), dtype=float).reshape(-1, 3, 3)
    n = struct.unpack("<I", b[80:84])[0]
    dt = np.dtype([("n", "<3f4"), ("v", "<9f4"), ("a", "<u2")])
    return np.frombuffer(b, dtype=dt, count=n, offset=84)["v"].reshape(-1, 3, 3).astype(float)


def slab(tris, thick):
    """closed thin solid from a flat, upward-facing triangle patch (MuJoCo refuses zero-volume meshes): top = patch, bottom = copy lowered by
    `thick`, side walls along the boundary edges (edges used by exactly one triangle)."""
    from collections import Counter
    key = lambda v: tuple(np.round(v, 7))
    cnt = Counter()
    for t in tris:
        for i in range(3):
            cnt[frozenset((key(t[i]), key(t[(i + 1) % 3])))] += 1
    out = [t for t in tris]
    down = np.array([0, 0, -thick])
    out += [t[::-1] + down for t in tris]
    for t in tris:
        for i in range(3):
            a, b = t[i], t[(i + 1) % 3]
            if cnt[frozenset((key(a), key(b)))] == 1:
                out += [np.array([a, b, b + down]), np.array([a, b + down, a + down])]
    return np.array(out)


def write_stl(path, tris):
    tris = np.asarray(tris, np.float32)
    n = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0]); n /= np.linalg.norm(n, axis=1, keepdims=True) + 1e-20
    with open(path, "wb") as f:
        f.write(b"pegholes generated by build_peg_hole.py".ljust(80, b" "))
        f.write(struct.pack("<I", len(tris)))
        for t, nn in zip(tris, n):
            f.write(struct.pack("<12fH", *nn, *t.reshape(-1), 0))


def mesh_props(tris):
    """volume, centroid, inertia tensor about centroid per unit density (mm units) for a closed mesh"""
    v0, v1, v2 = tris[:, 0], tris[:, 1], tris[:, 2]
    vol6 = np.einsum("ij,ij->i", v0, np.cross(v1, v2)); vol = vol6.sum() / 6
    cen = ((v0 + v1 + v2) / 4 * vol6[:, None]).sum(0) / 6 / vol
    return vol, cen


def main():
    global HOLES_FREE
    HOLES_FREE = HOLES_FREE or "--free-holes" in sys.argv
    peg = load_stl(CAD / "Peg_v1 - Peg_v1-1.STL")
    zc = peg.mean(axis=1)[:, 2]
    tri_sq, tri_ci = peg[zc < 100.05], peg[zc >= 100.05]
    vol, cen = mesh_props(peg)
    print(f"peg volume {vol/1e3:.1f} cm3, centroid (assembly frame, mm) {cen.round(2)}")
    T = lambda tris, shift: (tris - shift) * 1e-3
    shift = np.array([C_XY, C_XY, cen[2]])
    MESH.mkdir(parents=True, exist_ok=True)
    write_stl(MESH / "peg_sq.stl", T(tri_sq, shift)); write_stl(MESH / "peg_circ.stl", T(tri_ci, shift))
    # hole visuals in hole frames
    circ = load_stl(CAD / "Peg_v1 - Circle Hole^Assem1-1.STL"); sq = load_stl(CAD / "Peg_v1 - Square Hole^Assem1-1.STL")
    circ_h = np.stack([circ[..., 0] - C_XY, -(circ[..., 1] - C_XY), -(circ[..., 2] - 165.04)], -1) * 1e-3   # rot 180 deg about x
    sq_h = np.stack([sq[..., 0] - C_XY, sq[..., 1] - C_XY, sq[..., 2] - 45.04], -1) * 1e-3
    # the cavity floor (flat triangles at z = -41 mm) is its own mesh so it can get a different colour than the walls/body
    for nm, h in (("circle", circ_h), ("square", sq_h)):
        flat = np.ptp(h[:, :, 2], axis=1) < 1e-9
        floor = flat & (np.abs(h[:, :, 2].mean(1) + 0.041) < 1e-6)
        write_stl(MESH / f"hole_{nm}_vis.stl", h[~floor]); write_stl(MESH / f"hole_{nm}_floor.stl", slab(h[floor], 0.0003))
    # ---- collision primitives for the blocks (mm -> m)
    def sq_hole_bodies():
        g = []
        s, h, w, back, d = 0.070, 0.0467 / 2, 0.070 / 2, 0.003, 0.041
        g.append(f'<geom type="box" pos="0 0 {-d-back/2:.5f}" size="{w:.5f} {w:.5f} {back/2:.5f}"/>')
        t = w - h                         # wall thickness
        g.append(f'<geom type="box" pos="{h+t/2:.5f} 0 {-d/2:.5f}" size="{t/2:.5f} {w:.5f} {d/2:.5f}"/>')
        g.append(f'<geom type="box" pos="{-(h+t/2):.5f} 0 {-d/2:.5f}" size="{t/2:.5f} {w:.5f} {d/2:.5f}"/>')
        g.append(f'<geom type="box" pos="0 {h+t/2:.5f} {-d/2:.5f}" size="{h:.5f} {t/2:.5f} {d/2:.5f}"/>')
        g.append(f'<geom type="box" pos="0 {-(h+t/2):.5f} {-d/2:.5f}" size="{h:.5f} {t/2:.5f} {d/2:.5f}"/>')
        return g
    def circ_hole_bodies(n=48):
        r, w, back, d = 0.02774, 0.035, 0.003, 0.041
        g = [f'<geom type="box" pos="0 0 {-d-back/2:.5f}" size="{w:.5f} {w:.5f} {back/2:.5f}"/>']
        ang = np.arange(n + 1) * 2 * np.pi / n
        def outer(a):     # ray from centre to the outer square boundary
            c, s = np.cos(a), np.sin(a); k = w / max(abs(c), abs(s)); return np.array([k * c, k * s])
        for i in range(n):
            a0, a1 = ang[i], ang[i + 1]
            p = [r * np.array([np.cos(a0), np.sin(a0)]), r * np.array([np.cos(a1), np.sin(a1)]), outer(a1), outer(a0)]
            verts = []
            for z in (0.0, -d):
                for q in p: verts += [q[0], q[1], z]
            g.append('<geom type="mesh" mesh="cq%d"/>' % i)
            circ_meshes.append(f'<mesh name="cq{i}" vertex="' + " ".join(f"{v:.6f}" for v in verts) + '"/>')
        return g
    circ_meshes = []
    circ = circ_hole_bodies()
    sqg = sq_hole_bodies()
    assets = ['<mujoco model="peg_hole_assets">', '  <compiler angle="radian" meshdir="meshes"/>', '  <asset>',
              '    <mesh name="peg_sq" file="peg_sq.stl"/>', '    <mesh name="peg_circ" file="peg_circ.stl"/>',
              '    <mesh name="hole_circle_vis" file="hole_circle_vis.stl"/>', '    <mesh name="hole_square_vis" file="hole_square_vis.stl"/>',
              '    <mesh name="hole_circle_floor" file="hole_circle_floor.stl"/>', '    <mesh name="hole_square_floor" file="hole_square_floor.stl"/>']
    assets += ["    " + m for m in circ_meshes] + ['  </asset>', '</mujoco>']
    (OUT / "peg_hole_assets.xml").write_text("\n".join(assets))
    fr = 'friction="0.8 0.005 0.0005" solref="0.004 1" solimp="0.95 0.99 0.001" condim="4"'
    peg_body = f"""<body name="peg" pos="0 0 0.3">
      <freejoint name="peg_free"/>
      <inertial pos="0 0 0" mass="{PEG_MASS_KG}" diaginertia="{PEG_MASS_KG*(0.0325**2+0.2**2/12)/2:.3e} {PEG_MASS_KG*(0.0325**2+0.2**2/12)/2:.3e} {PEG_MASS_KG*0.0325**2/2:.3e}"/>
      <geom type="mesh" mesh="peg_sq" contype="0" conaffinity="0" rgba="0.9 0.9 0.9 1"/>
      <geom type="mesh" mesh="peg_circ" contype="0" conaffinity="0" rgba="0.15 0.15 0.15 1"/>
      <!-- collision = primitives (mesh-mesh contacts were unstable at the rim); 8 mm square->round loft has no collision geom -->
      <geom name="peg_sq_col" type="box" pos="0 0 {-0.05575:.5f}" size="0.02075 0.02075 0.0475" {fr} rgba="0 0 0 0"/>
      <geom name="peg_circ_col" type="cylinder" pos="0 0 0.04834" size="0.025 0.04841" {fr} rgba="0 0 0 0"/>
    </body>"""
    # real blocks: square-hole block white with a black cavity floor, circle-hole block black with a white floor (user, 2026-09-26)
    BODY_FLOOR = {"hole_square": ("0.92 0.92 0.93 1", "0.04 0.04 0.04 1"), "hole_circle": ("0.05 0.05 0.05 1", "0.92 0.92 0.93 1")}
    def hole_body(name, pos, vis, prims):
        m_ = HOLE_MASS_KG
        inert = f'<inertial pos="0 0 -0.022" mass="{m_}" diaginertia="{m_/12*(0.07**2+0.044**2):.3e} {m_/12*(0.07**2+0.044**2):.3e} {m_/12*(0.07**2+0.07**2):.3e}"/>'
        fj = f'<freejoint name="{name}_free"/>' if HOLES_FREE else ""
        return (f'<body name="{name}" pos="{pos}">{fj}{inert}<geom type="mesh" mesh="{vis}" contype="0" conaffinity="0" rgba="{BODY_FLOOR[name][0]}"/><geom type="mesh" mesh="{vis.replace('_vis', '_floor')}" mass="0" contype="0" conaffinity="0" rgba="{BODY_FLOOR[name][1]}"/>\n      '
                + "\n      ".join(p.replace("/>", f' {fr} rgba="0.2 0.2 0.22 0"/>') for p in prims) + "\n    </body>")
    test = f"""<mujoco model="peg_hole_test"><include file="peg_hole_assets.xml"/>
  <option timestep="0.001" integrator="implicitfast"/>
  <worldbody><geom name="table" type="plane" size="1 1 0.1" {fr}/>
    {hole_body("hole_square", "-0.15 0 0.041", "hole_square_vis", sqg)}
    {hole_body("hole_circle", "0.15 0 0.041", "hole_circle_vis", circ)}
    {peg_body}
  </worldbody></mujoco>"""
    (OUT / "peg_hole_test.xml").write_text(test)
    print("wrote assets in", OUT)


if __name__ == "__main__":
    sys.exit(main())
