#!/usr/bin/env python3
"""Generate the MuJoCo model (+ tree URDF + metadata) of the PincOpen gripper, revision TRY3.

Source geometry: cad/PincOpen_Gripper/solidworks/try2/print_3/TRY2_ASS - *.STL -- part meshes exported IN ASSEMBLY
COORDINATES (mm).  try3 is identical to try2 for every linkage part (cmp of the .SLDPRT files: Cam, Driving/Internal/
External/Distal rods, Distal_Shell, Tip_Support, Top_Plate, Part1, Mount ARM ... are byte-identical).  Per the user the robot
uses the try2 `Removable_Tip` (NOT the xense tip); `Tip_Support` is the rubber pad that goes onto the Removable_Tip, so the
contact surface = the inner face of Tip_Support.  The SolidWorks URDF export
(URDF/try_1) is NOT used: it is the older try1 linkage (different lever lengths) and has degenerate joints.

Mechanism (per finger, planar; assembly x = finger direction, y = pinch direction, z = hinge axis):
  servo -> CAM (2 pins 180 deg apart, r 11.0 mm) -> DR (32.6 mm) -> IR (rigid rocker pinned to the base; arms 16.4 / 44.9 mm)
        -> Tip body (Distal_Rod + Distal_Shell + Tip_Support + Removable_Tip, rigid; pinned to the IR far end)
  OR (external rod, 40.0 mm, pinned to the base) closes the loop on the tip body 11.5 mm from the IR pivot.
  1 DOF per finger; both driven by one cam joint.  Unlike try1 it is NOT an exact parallelogram (base pivots 13.7 mm apart vs
  11.5 mm on the tip), so the tips rotate a little while closing (measured in verify_pincopen.py).
Pivots were measured as circular through-holes in the meshes (find_pivots.py).  Loops = MuJoCo `connect` constraints.

Gripper frame G (metres): origin on the cam axis at mid finger-plane; +x = fingers/tool axis, z = jaw (pinch) direction
(fingers at z ~ -33..+40 mm), y = hinge axis (y_g = -(z_assembly - 50.5)).  cam_joint > 0 = CCW in the x-z plane.
"""
import json
import struct
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
ASSETS = HERE / "assets" / "pincopen"
MESHES = ASSETS / "meshes"
CAD_ROOT = HERE.parent / "cad"
SRC = CAD_ROOT / "PincOpen_Gripper" / "solidworks" / "try2" / "print_3"
PREFIX = "TRY2_ASS - "
O_A = np.array([77.7, 77.4, 50.5])          # assembly-frame point that becomes the gripper-frame origin (mm)


def load_stl(path):
    import re
    b = Path(path).read_bytes()
    if b[:5] == b"solid" and b"facet" in b[:400]:
        return np.array(re.findall(rb"vertex\s+(\S+)\s+(\S+)\s+(\S+)", b), dtype=float).reshape(-1, 3, 3)
    n = struct.unpack("<I", b[80:84])[0]
    dt = np.dtype([("n", "<3f4"), ("v", "<9f4"), ("a", "<u2")])
    return np.frombuffer(b, dtype=dt, count=n, offset=84)["v"].reshape(-1, 3, 3).astype(float)


def write_stl(path, tris):
    tris = np.asarray(tris, np.float32)
    n = np.cross(tris[:, 1] - tris[:, 0], tris[:, 2] - tris[:, 0]); n /= np.linalg.norm(n, axis=1, keepdims=True) + 1e-20
    with open(path, "wb") as f:
        f.write(b"pincopen try3 generated by build_pincopen.py".ljust(80, b" "))
        f.write(struct.pack("<I", len(tris)))
        for t, nn in zip(tris, n):
            f.write(struct.pack("<12fH", *nn, *t.reshape(-1), 0))


def to_G(pts_mm):
    """assembly (xa, ya, za) [mm] -> gripper frame (x, y, z) [m].  x_g = xa - 77.7, y_g = -(za - 50.5), z_g = ya - 77.4"""
    p = np.asarray(pts_mm, float) - O_A
    return np.stack([p[..., 0], -p[..., 2], p[..., 1]], -1) * 1e-3


def mesh_mass_props(tris_m):
    """volume, centroid, inertia about the centroid per unit density (SI, closed mesh)"""
    v0, v1, v2 = tris_m[:, 0], tris_m[:, 1], tris_m[:, 2]
    d = np.einsum("ij,ij->i", v0, np.cross(v1, v2))
    vol = d.sum() / 6
    cen = ((v0 + v1 + v2) / 4 * d[:, None]).sum(0) / 6 / vol
    # covariance integral via tetrahedra about origin
    C = np.zeros((3, 3))
    for a, b, c, dd in zip(v0, v1, v2, d):
        V = np.array([a, b, c])
        S = V.T @ V + np.outer(V.sum(0), V.sum(0))
        C += dd / 120 * S
    I0 = np.trace(C) * np.eye(3) - C
    I = I0 - vol * ((cen @ cen) * np.eye(3) - np.outer(cen, cen))
    return vol, cen, I


# ---- parts (assembly meshes) grouped into rigid bodies
PARTS = {
    "base": ["Bottom_Plate-1", "Top_Plate-1", "Part1-2", "Mount ARM-1", "XMH430 mount-1", "DUMMY_DC12.stp-1"],
    "cam": ["Cam-1"],
    "dr_L": ["Driving_Rod-1"], "dr_R": ["Driving_Rod-2"],      # assembly y<77 (Driving_Rod-2 pin (87.2,83.0)) = "R"; y>77 = "L"
    "ir_L": ["Internal_Rod-2"], "ir_R": ["Internal_Rod-1"],
    "or_L": ["External_Rod-2"], "or_R": ["External_Rod-1"],
    "tip_L": ["Distal_Rod-1", "Distal_Shell-2", "Tip_Support-2", "Removable_Tip-2"],
    "tip_R": ["Distal_Rod-2", "Distal_Shell-1", "Tip_Support-1", "Removable_Tip-1"],
}
# masses [kg] carried over from the SolidWorks export of the same parts (try_1.urdf): base 0.184, cam 0.0046, DR 0.0017, IR 0.0056, OR 0.0032, tip body 0.0122
MASS = dict(base=0.18391, cam=0.0045994, dr_L=0.0016524, dr_R=0.0016524, ir_L=0.0055604, ir_R=0.0055604,
            or_L=0.0032465, or_R=0.0032465, tip_L=0.012199, tip_R=0.012199)

# ---- pivots measured on the meshes, assembly frame (x_a, y_a) mm.  L = upper finger (y_a > 77), R = lower finger.
PIV_A = {
    "cam_axis": (77.7, 77.4),
    "cam_pin_L": (68.4, 71.6), "cam_pin_R": (87.2, 83.0),
    "dr_ir_L": (75.5, 103.4), "dr_ir_R": (75.9, 52.4),
    "ir_base_L": (91.2, 108.5), "ir_base_R": (91.0, 46.6),
    "ir_tip_L": (134.0, 121.6), "ir_tip_R": (133.4, 31.2),
    "or_base_L": (95.8, 121.4), "or_base_R": (95.8, 33.4),
    "or_tip_L": (134.0, 133.1), "or_tip_R": (133.4, 19.7),
}
PIV = {k: (v[0] - O_A[0], v[1] - O_A[1]) for k, v in PIV_A.items()}       # (x_g, z_g) in mm
# pad = Tip_Support gripping face (inner y_a face): L 109.1, R 43.7 (assembly, at the exported pose); pad box: x 148..168 mm, 25.6 mm wide, 4 mm thick
PAD_FACE_A = {"L": 109.1, "R": 43.7}
PAD_X_A = (148.0, 168.0)
# contact face = inner face of Tip_Support (rubber).  Collision box = the 4 mm of rubber behind that face.
PAD_THICK_MM = 4.0
PEG_SQ_MM, PEG_ROUND_MM = 41.5, 50.0                 # peg sections held in the circular-hole / square-hole tasks
PLATEAU_CIRC_TASK, PLATEAU_SQR_TASK = 0.569, 0.505   # per-task median recorded gripper value while holding (datasets)
MOUNT_ARM_BACK_X_A = 27.5   # assumed flange plane (assembly x, mm).  Was 21.8 (Mount ARM back face); moved 5.7 mm toward the tips so that the pad centre sits 14.5 mm above the dataset TCP: at grasp the TCP is 13-16 mm below the axis of the lying peg (TCP z 6-7 mm vs axis 19-23 mm), and the pads must straddle the peg axis
MOUNT_SIGN = +1          # +1: gripper +y (hinge axis) points toward the robot base at home (user: "pin axes face the base"); -1: away
PAD_Z_A = (38.1, 63.8)


def P3(name):
    x, z = PIV[name]
    return np.array([x * 1e-3, 0.0, z * 1e-3])


# ---------------- planar six-bar solver (reference for verification + cam<->gap table) ----------------
def circ_int(c0, r0, c1, r1, prefer):
    d = np.linalg.norm(c1 - c0)
    if d > r0 + r1 or d < abs(r0 - r1) or d == 0:
        return None
    a = (r0 * r0 - r1 * r1 + d * d) / (2 * d); h2 = r0 * r0 - a * a
    if h2 < 0:
        return None
    e = (c1 - c0) / d; n = np.array([-e[1], e[0]]); h = np.sqrt(h2)
    cands = [c0 + a * e + h * n, c0 + a * e - h * n]
    return min(cands, key=lambda p: np.linalg.norm(p - prefer))


def rot(v, a):
    c, s = np.cos(a), np.sin(a)
    return np.array([c * v[0] - s * v[1], s * v[0] + c * v[1]])


def finger_pose(side, dtheta, prev=None):
    """tip-body pose (rotation dphi [rad] about the IR-tip pivot, pivot position) for a cam rotation dtheta from the exported pose.
    all in (x_g, z_g) mm.  prev = dict of previous branch points."""
    A = {k: np.array(PIV[k + "_" + side]) for k in ("cam_pin", "dr_ir", "ir_base", "ir_tip", "or_base", "or_tip")}
    C = np.array(PIV["cam_axis"])
    K = C + rot(A["cam_pin"] - C, dtheta)
    Ld = np.linalg.norm(A["dr_ir"] - A["cam_pin"])
    rn = np.linalg.norm(A["dr_ir"] - A["ir_base"])
    N = circ_int(A["ir_base"], rn, K, Ld, prev["N"] if prev else A["dr_ir"])
    if N is None:
        return None
    n0 = A["dr_ir"] - A["ir_base"]; n1 = N - A["ir_base"]
    dpsi = np.arctan2(n1[1], n1[0]) - np.arctan2(n0[1], n0[0])
    P1 = A["ir_base"] + rot(A["ir_tip"] - A["ir_base"], dpsi)
    t0 = A["or_tip"] - A["ir_tip"]; lt = np.linalg.norm(t0); Lo = np.linalg.norm(A["or_tip"] - A["or_base"])
    P2 = circ_int(A["or_base"], Lo, P1, lt, prev["P2"] if prev else A["or_tip"])
    if P2 is None:
        return None
    dphi = np.arctan2(*(P2 - P1)[::-1]) - np.arctan2(t0[1], t0[0])
    return dict(N=N, P1=P1, P2=P2, dphi=dphi, side=side)


def pad_center_z(side, pose):
    """z_g (mm) of the pad's inner face at the pad centre for a given tip pose (rigid about P1)"""
    A = np.array(PIV["ir_tip_" + side])
    face_y = PAD_FACE_A[side] - O_A[1]     # Tip_Support inner face (contact surface)
    xc = 0.5 * (PAD_X_A[0] + PAD_X_A[1]) - O_A[0]
    p0 = np.array([xc, face_y])
    return (pose["P1"] + rot(p0 - A, pose["dphi"]))[1]


def gap_table():
    def sweep(degs):
        prev = {"L": None, "R": None}; out = []
        for dd in degs:
            pL = finger_pose("L", np.radians(dd), prev["L"]); pR = finger_pose("R", np.radians(dd), prev["R"])
            if pL is None or pR is None:
                break
            prev = {"L": pL, "R": pR}
            out.append((float(dd), float(pad_center_z("L", pL) - pad_center_z("R", pR))))    # TRUE pad gap (pads included)
        return out
    return sorted(sweep(np.arange(-1, -200.01, -1.0)) + sweep(np.arange(0, 90.01, 1.0)))


# ---------------- MJCF ----------------
def fmt(v, n=6):
    return " ".join(f"{x:.{n}f}" for x in v)


def build():
    MESHES.mkdir(parents=True, exist_ok=True)
    body_meshes, props = {}, {}
    for body, parts in PARTS.items():
        tris_all = []
        for part in parts:
            t = to_G(load_stl(SRC / f"{PREFIX}{part}.STL"))
            name = part.replace(" ", "_").replace(".", "_")
            # MuJoCo merges identical vertices and smooths normals across them (2.3.x has no flat-shading option), which makes flat-faced
            # CAD parts render as blobs.  Pull each triangle's vertices 5 um toward its centroid so vertices stay unique => flat shading.
            cen = t.mean(axis=1, keepdims=True)
            write_stl(MESHES / f"{name}.stl", t + (cen - t) * 0.0004 / np.maximum(np.linalg.norm(cen - t, axis=2, keepdims=True), 1e-9) * 0.01)
            body_meshes.setdefault(body, []).append(name)
            tris_all.append(t)
        T = np.concatenate(tris_all)
        vol, cen, I = mesh_mass_props(T) if body not in ("base",) else (None, None, None)
        props[body] = (vol, cen, I)
    return body_meshes, props


def mjcf(gap):
    body_meshes, props = build()
    dd = np.array([g[0] for g in gap]); gp = np.array([g[1] for g in gap])
    i_open = int(np.argmax(gp))
    valid_closed = dd[gp > 0.5]
    lo_deg, hi_deg = float(valid_closed.min()), float(dd[i_open]) - 3.0     # stay 3 deg short of the toggle (dead) point
    rng = (np.radians(lo_deg), np.radians(hi_deg))
    out = []
    A = out.append
    A('<mujoco model="pincopen_try3">')
    A('  <!-- GENERATED by ur10sim/build_pincopen.py (gripper revision try3); edit the generator, not this file -->')
    A('  <compiler angle="radian" meshdir="meshes" autolimits="true"/>')
    A('  <option timestep="0.001" integrator="implicitfast" impratio="10" noslip_iterations="3"/>')
    A('  <default>')
    A('    <joint armature="2e-5" damping="0.005"/>')
    A('    <default class="visual"><geom type="mesh" contype="0" conaffinity="0" group="1" rgba="0.85 0.85 0.88 1"/></default>')
    A('    <default class="pad"><geom type="box" group="3" friction="1.2 0.02 0.002" condim="4" solref="0.004 1" solimp="0.95 0.99 0.001" margin="0.0005" rgba="0.1 0.6 0.1 0.3"/></default>')
    A('  </default>')
    A('  <asset>')
    for b, ms in body_meshes.items():
        for m in ms:
            A(f'    <mesh name="{m}" file="{m}.stl"/>')
    A('  </asset>')

    def inertial(body, pivot):
        vol, cen, I = props[body]
        if vol is None:   # base: mass only, COM at origin-ish (approximate; refine when mount/servo CAD is added)
            return f'<inertial pos="0.0 0 0" mass="{MASS[body]:.6f}" diaginertia="1e-4 1e-4 1e-4"/>'
        rho = MASS[body] / vol
        Ic = I * rho
        return (f'<inertial pos="{fmt(cen - pivot)}" mass="{MASS[body]:.6f}" '
                f'fullinertia="{Ic[0,0]:.4e} {Ic[1,1]:.4e} {Ic[2,2]:.4e} {Ic[0,1]:.4e} {Ic[0,2]:.4e} {Ic[1,2]:.4e}"/>')

    def geoms(body, pivot):
        return "\n".join(f'        <geom class="visual" mesh="{m}" pos="{fmt(-pivot)}"/>' for m in body_meshes[body])

    # dr/ir/tip/or hinges had NO range at all (limited="false") -- a real gripper's pivots have hard
    # mechanical stops; without them, nothing stops MuJoCo's loop-closure solver (the <connect> equality
    # constraints below) from settling into the OTHER valid solution for a closed 4-bar linkage under a
    # hard enough perturbation (fast/asymmetric contact) -- same joint angles, loop-closure still
    # satisfied ("kinematically valid"), but the finger is flipped ~180 deg about its own axis. Measured
    # normal operating range across 6 full open/close cycles (see CHANGELOG.md 2026-09-29), +-0.5 rad
    # margin -- comfortably covers real operation, nowhere near the ~3.14 rad needed to reach the flip.
    LINK_RANGE = {
        "dr":  (-1.25, 2.00),
        "ir":  (-1.40, 1.50),
        "tip": (-2.05, 1.70),
        "or":  (-1.55, 1.75),
    }

    def hinge(name, rng=None, damping=0.001):
        r = f' range="{rng[0]:.5f} {rng[1]:.5f}" limited="true"' if rng else ""
        return f'<joint name="{name}" type="hinge" axis="0 -1 0"{r} damping="{damping}"/>'

    A('  <worldbody>')
    A('    <body name="pincopen_base" pos="0 0 0">')
    A('      ' + inertial("base", np.zeros(3)))
    A("\n".join(f'      <geom class="visual" mesh="{m}"/>' for m in body_meshes["base"]))
    A('      <site name="jaw_center" pos="0.0850 0 0.0" size="0.002" rgba="1 0 0 1"/>')
    cam_p = P3("cam_axis")
    A(f'      <body name="cam" pos="{fmt(cam_p)}">')
    A('        ' + inertial("cam", cam_p)); A(f'        {hinge("cam_joint", rng, 0.02)}'); A(geoms("cam", cam_p))
    for s in ("L", "R"):
        pin = P3("cam_pin_" + s)
        A(f'        <body name="dr_{s}" pos="{fmt(pin - cam_p)}">')
        A('          ' + inertial("dr_" + s, pin)); A(f'          {hinge("dr_" + s + "_joint", LINK_RANGE["dr"])}'); A(geoms("dr_" + s, pin)); A('        </body>')
    A('      </body>')
    for s in ("L", "R"):
        irp = P3("ir_base_" + s)
        A(f'      <body name="ir_{s}" pos="{fmt(irp)}">')
        A('        ' + inertial("ir_" + s, irp)); A(f'        {hinge("ir_" + s + "_joint", LINK_RANGE["ir"])}'); A(geoms("ir_" + s, irp))
        tp = P3("ir_tip_" + s)
        A(f'        <body name="tip_{s}" pos="{fmt(tp - irp)}">')
        A('          ' + inertial("tip_" + s, tp)); A(f'          {hinge("tip_" + s + "_joint", LINK_RANGE["tip"])}'); A(geoms("tip_" + s, tp))
        yface = PAD_FACE_A[s]
        # pad box: inner face at yface, 4 mm thick toward the outside of the jaw
        sign = +1 if s == "L" else -1     # L finger is at larger y_a; the rubber extends from the contact face AWAY from the jaw centre
        cy_a = yface + sign * PAD_THICK_MM / 2
        centre = to_G(np.array([0.5 * (PAD_X_A[0] + PAD_X_A[1]), cy_a, 0.5 * (PAD_Z_A[0] + PAD_Z_A[1])]))
        half = np.array([0.5 * (PAD_X_A[1] - PAD_X_A[0]), 0.5 * (PAD_Z_A[1] - PAD_Z_A[0]), PAD_THICK_MM / 2]) * 1e-3      # (x, y_g(=za), z_g(=ya))
        A(f'          <geom class="pad" name="pad_{s}" pos="{fmt(centre - tp)}" size="{half[0]:.5f} {half[1]:.5f} {half[2]:.5f}"/>')
        A('        </body>'); A('      </body>')
        orp = P3("or_base_" + s)
        A(f'      <body name="or_{s}" pos="{fmt(orp)}">')
        A('        ' + inertial("or_" + s, orp)); A(f'        {hinge("or_" + s + "_joint", LINK_RANGE["or"])}'); A(geoms("or_" + s, orp)); A('      </body>')
    A('    </body>'); A('  </worldbody>')
    A('  <equality>')
    for s in ("L", "R"):
        A(f'    <connect name="loop_dr_ir_{s}" body1="dr_{s}" body2="ir_{s}" anchor="{fmt(P3("dr_ir_" + s) - P3("cam_pin_" + s))}" solref="0.006 1" solimp="0.95 0.99 0.001"/>')
        A(f'    <connect name="loop_or_tip_{s}" body1="or_{s}" body2="tip_{s}" anchor="{fmt(P3("or_tip_" + s) - P3("or_base_" + s))}" solref="0.006 1" solimp="0.95 0.99 0.001"/>')
    A('  </equality>')
    A('  <actuator>')
    A(f'    <general name="cam_act" joint="cam_joint" gainprm="60" biastype="affine" biasprm="0 -60 -1.0" ctrlrange="{rng[0]:.5f} {rng[1]:.5f}" forcerange="-1 1"/>')
    A('  </actuator>'); A('</mujoco>')
    return "\n".join(out), dict(cam_range_rad=[float(rng[0]), float(rng[1])])


def rot_to_rpy(R):
    p = np.arcsin(np.clip(-R[2, 0], -1, 1))
    if abs(np.cos(p)) > 1e-6:
        return np.array([np.arctan2(R[2, 1], R[2, 2]), p, np.arctan2(R[1, 0], R[0, 0])])
    return np.array([0.0, p, np.arctan2(-R[0, 1], R[1, 1])])


def urdf(cam_range):
    """tree-only URDF, link frame = world-aligned hinge frame at the pivot; meshes are already in gripper-frame metres."""
    body_meshes, props = build()
    piv = {"base_link": np.zeros(3), "cam": P3("cam_axis")}
    parent = {"cam": "base_link"}
    for s in ("L", "R"):
        piv.update({f"dr_{s}": P3("cam_pin_" + s), f"ir_{s}": P3("ir_base_" + s), f"tip_{s}": P3("ir_tip_" + s), f"or_{s}": P3("or_base_" + s)})
        parent.update({f"dr_{s}": "cam", f"ir_{s}": "base_link", f"tip_{s}": f"ir_{s}", f"or_{s}": "base_link"})
    L = ['<?xml version="1.0"?>',
         '<!-- GENERATED by build_pincopen.py (gripper revision try3). TREE ONLY: closed loops (dr_ir_*: dr_L/R <-> ir_L/R, or_tip_*: or_L/R <-> tip_L/R)',
         '     cannot be expressed in URDF; see pincopen_meta.json "loop_closures"; pincopen.xml has them as MuJoCo connect constraints.',
         '     Planar mechanism in the x-z plane, every joint revolute about -Y, link frames world-aligned at the pivots, units m. -->',
         '<robot name="pincopen_try3">']
    for name, pv in piv.items():
        key = "base" if name == "base_link" else name
        m = MASS[key]
        vol, cen, I = props[key]
        if vol is None:
            com, Ic = np.zeros(3), np.diag([1e-4] * 3)
        else:
            com, Ic = cen - pv, I * (m / vol)
        vis = "".join(f'<visual><origin xyz="{fmt(-pv)}"/><geometry><mesh filename="meshes/{mm}.stl"/></geometry></visual>' for mm in body_meshes[key])
        L.append(f'  <link name="{name}"><inertial><origin xyz="{fmt(com)}"/><mass value="{m:.6f}"/>'
                 f'<inertia ixx="{Ic[0,0]:.4e}" ixy="{Ic[0,1]:.4e}" ixz="{Ic[0,2]:.4e}" iyy="{Ic[1,1]:.4e}" iyz="{Ic[1,2]:.4e}" izz="{Ic[2,2]:.4e}"/></inertial>{vis}</link>')
    for name, par in parent.items():
        lim = (f'<limit lower="{cam_range[0]:.5f}" upper="{cam_range[1]:.5f}" effort="3" velocity="10"/>' if name == "cam"
               else '<limit lower="-3.14159" upper="3.14159" effort="1" velocity="10"/>')
        L.append(f'  <joint name="{name}_joint" type="revolute"><parent link="{par}"/><child link="{name}"/>'
                 f'<origin xyz="{fmt(piv[name] - piv[par])}" rpy="0 0 0"/><axis xyz="0 -1 0"/>{lim}</joint>')
    L.append('</robot>')
    return "\n".join(L)


def frac_map(tab):
    """recorded gripper fraction (0 open .. 1 closed) <-> cam angle:  frac = (a_open - cam) / span, FITTED from the two grasp plateaus
    (2 equations, 2 unknowns): frac 0.569 holds the 41.5 mm square section, 0.505 holds the 50 mm round section.  Everything else
    (open gap at frac 0, frac at which the rubber pads meet) is then a PREDICTION to compare with the data (max recorded 0.93)."""
    tab = np.array(tab)
    imax = int(np.argmax(tab[:, 1]))
    br = tab[: imax + 1]                                   # ascending angle, gap increasing up to the toggle point
    ang = lambda gap: float(np.interp(gap, br[:, 1], br[:, 0]))
    a_sq, a_rd = ang(PEG_SQ_MM), ang(PEG_ROUND_MM)         # cam angle where the gap equals each peg section
    span = (a_rd - a_sq) / (PLATEAU_CIRC_TASK - PLATEAU_SQR_TASK)
    a_open = a_rd + PLATEAU_SQR_TASK * span
    fr = np.linspace(0, 1, 21)
    cam = a_open - fr * span
    gap = np.minimum.accumulate(np.maximum(np.interp(cam, tab[:, 0], tab[:, 1]), 0.0))    # monotone: past pad contact the gap stays ~0
    at = lambda f: float(np.interp(a_open - f * span, tab[:, 0], tab[:, 1]))
    contact = float(tab[tab[:, 1] > 0.5][:, 0].min())
    return dict(a_open_deg=float(a_open), span_deg=float(span), implied_cam_to_servo_ratio=float(span / 119.0), servo_span_deg_from_recorder=119.0,
                frac=[float(x) for x in fr], cam_deg=[float(x) for x in cam], gap_mm=[float(x) for x in gap],
                PREDICTED_gap_mm_at_frac_0=at(0.0), PREDICTED_frac_at_pad_contact=float((a_open - contact) / span),
                data_max_recorded_frac=0.93, gap_mm_at_plateau_circle_task=at(PLATEAU_CIRC_TASK), gap_mm_at_plateau_square_task=at(PLATEAU_SQR_TASK))


def mount_info():
    """flange -> gripper-frame transform.
    Orientation (user): at home (joints 0,-90,90,-90,-90,90) the hinge ('pin') axes point toward the robot base, i.e. along the base x axis.
    FK at home gives flange x_f = +x_base, y_f = -y_base, z_f = -z_base (tool pointing down).  Tool axis x_g = z_f, hinge axis
    y_g = s*x_f, jaw axis z_g = x_g x y_g = s*y_f.  s=+1: +y_g points toward the base (assumed; flip MOUNT_SIGN otherwise).
    Position: the flange plane is taken as the BACK FACE of the Mount ARM plate (x_a = 21.8 mm -> x_g = -55.9 mm), on the plate's centre
    line (y_g = -1.1 mm, z_g = 0).  Cross-check: the 145 mm TCP then lands at x_g = 89.1 mm, 3 mm short of the fingertip end (92.3 mm), and
    the dataset grasps (TCP z ~ 6 mm above the table while holding a lying peg, i.e. pad centre ~9 mm higher) agree with that."""
    sgn = MOUNT_SIGN
    R = np.array([[0.0, sgn, 0.0], [0.0, 0.0, sgn], [1.0, 0.0, 0.0]])       # columns = x_g, y_g, z_g expressed in the flange frame
    xf_g = (MOUNT_ARM_BACK_X_A - O_A[0]) * 1e-3                              # flange plane x in the gripper frame (m), negative
    f_in_g = np.array([xf_g, -1.1e-3, 0.0])                                  # flange origin in G
    p_fg = R @ (-f_in_g)                                                     # G origin in F = R_FG @ (-p_GF)
    tcp_x_g = xf_g * 1e3 + 145.0
    return dict(sign=sgn, R_flange_gripper=R.tolist(), p_flange_gripper_m=[float(v) for v in p_fg], tcp_offset_mm=145.0,
                flange_plane_x_g_mm=xf_g * 1e3, tcp_x_g_mm=tcp_x_g, fingertip_end_x_g_mm=170.0 - O_A[0],
                pad_centre_x_g_mm=0.5 * (PAD_X_A[0] + PAD_X_A[1]) - O_A[0],
                note="orientation sign ASSUMED; position from the Mount ARM back face, see docstring/README")


def main():
    gap = gap_table()
    xml, extra = mjcf(gap)
    (ASSETS / "pincopen.xml").write_text(xml)
    (ASSETS / "pincopen.urdf").write_text(urdf(extra["cam_range_rad"]))
    lens = lambda a, b, s: float(np.linalg.norm(np.array(PIV[a + s]) - np.array(PIV[b + s])))
    meta = dict(
        revision="try3 linkage/plates + try2 Removable_Tip with Tip_Support rubber pads (from try2/print_3 assembly STLs); no xense tip; camera mount not modelled",
        frame="gripper frame G: origin on the cam axis, +x fingers/tool axis, z jaw direction, y = hinge axis; xml in m/rad, tables in mm/deg",
        pivots_gripper_frame_xz_mm={k: list(v) for k, v in PIV.items()}, pivots_assembly_frame_xy_mm=PIV_A,
        links_mm=dict(crank_radius=lens("cam_pin_", "cam_pin_", "L") * 0 + float(np.linalg.norm(np.array(PIV["cam_pin_L"]) - np.array(PIV["cam_axis"]))),
                      driving_rod=[lens("cam_pin", "dr_ir", "_" + s) if False else float(np.linalg.norm(np.array(PIV["cam_pin_" + s]) - np.array(PIV["dr_ir_" + s]))) for s in "LR"],
                      ir_near_arm=[float(np.linalg.norm(np.array(PIV["dr_ir_" + s]) - np.array(PIV["ir_base_" + s]))) for s in "LR"],
                      ir_far_arm=[float(np.linalg.norm(np.array(PIV["ir_tip_" + s]) - np.array(PIV["ir_base_" + s]))) for s in "LR"],
                      outer_rod=[float(np.linalg.norm(np.array(PIV["or_tip_" + s]) - np.array(PIV["or_base_" + s]))) for s in "LR"],
                      tip_coupler=[float(np.linalg.norm(np.array(PIV["or_tip_" + s]) - np.array(PIV["ir_tip_" + s]))) for s in "LR"],
                      base_pivot_separation=[float(np.linalg.norm(np.array(PIV["or_base_" + s]) - np.array(PIV["ir_base_" + s]))) for s in "LR"]),
        loop_closures=[dict(name=f"loop_dr_ir_{s}", between=[f"dr_{s}", f"ir_{s}"]) for s in "LR"] + [dict(name=f"loop_or_tip_{s}", between=[f"or_{s}", f"tip_{s}"]) for s in "LR"],
        pad_faces_assembly_y_mm=PAD_FACE_A, mount=mount_info(),
        gap_table_deg_mm=[[a, b] for a, b in gap], frac_map=frac_map(gap), **extra)
    (ASSETS / "pincopen_meta.json").write_text(json.dumps(meta, indent=1))
    print("wrote", ASSETS)
    print("cam range (deg)", np.degrees(extra["cam_range_rad"]).round(1), " max gap mm", round(max(b for _, b in gap), 1),
          " gap at export pose", round(dict(gap)[0.0], 1))
    fm = meta["frac_map"]
    print("frac map (fit on plateaus): span", round(fm["span_deg"], 1), "deg, open at cam", round(fm["a_open_deg"], 1),
          "| PREDICTED gap@frac0", round(fm["PREDICTED_gap_mm_at_frac_0"], 1), "mm, pad contact at frac", round(fm["PREDICTED_frac_at_pad_contact"], 2), "(data max 0.93)")


if __name__ == "__main__":
    sys.exit(main())
